[package]
name = "grafium"
version = "0.0.37"
edition = "2021"

[dependencies]
tauri = { version = "2", features = ["custom-protocol", "devtools"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
grafium_core = { path = "../../core", package = "grafium-core" }
tokio = { version = "1", features = ["full"] }
notify = "6"

[target.'cfg(target_os = "linux")'.dependencies]
webkit2gtk = "2.0.2"
gtk = "0.18"
gdk = "0.18"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[lib]
name = "grafium_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
