//! Scraping YouTube's (or any `yt-dlp`-supported site's) already-existing
//! captions instead of re-transcribing audio with Whisper.
//!
//! Most YouTube videos already have either creator-uploaded captions or
//! YouTube's own auto-generated ones — fetching those via `yt-dlp` is
//! instant and needs nothing beyond the `yt-dlp` binary already required by
//! [`crate::media::ingest`], unlike [`crate::media::transcribe`] which
//! needs a multi-gigabyte Whisper model and a C++ build of whisper.cpp.
//! This module is deliberately unconditional (no Cargo feature gate) so
//! "does this video already have captions?" is always cheap to check
//! before ever falling back to local transcription.
//!
//! Two-step by design: `--write-sub` (creator captions) and
//! `--write-auto-sub` (YouTube's auto captions) are tried as *separate*
//! `yt-dlp` invocations rather than one combined call, specifically so the
//! caller can tell which kind it got — creator captions are generally far
//! more accurate, and that distinction is worth surfacing (see
//! [`crate::media::types::TranscriptSource`]).

use std::path::Path;
use std::process::{Command, Stdio};

use crate::error::{CoreError, Result};
use crate::media::tooling;
use crate::media::types::{Transcript, TranscriptSegment, TranscriptSource};

/// Metadata about a remote video, fetched without downloading it.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct VideoMetadata {
    pub title: Option<String>,
    pub uploader: Option<String>,
    pub duration_seconds: Option<f64>,
}

/// Fetches title/uploader/duration for `url` via `yt-dlp --dump-json
/// --skip-download`, without downloading any audio or video. Used to fill
/// in the generated note's frontmatter regardless of which transcript
/// source ends up being used.
pub fn fetch_metadata(url: &str) -> Result<VideoMetadata> {
    let output = Command::new("yt-dlp")
        .args(["--dump-json", "--skip-download", "--no-playlist", url])
        .stdin(Stdio::null())
        .output()
        .map_err(|e| tooling::missing_tool_error("yt-dlp", tooling::YT_DLP_INSTALL_HINT, e))?;
    if !output.status.success() {
        return Err(CoreError::Other(format!(
            "yt-dlp failed to fetch metadata ({}): {}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    let json: serde_json::Value = serde_json::from_slice(&output.stdout)
        .map_err(|e| CoreError::Other(format!("failed to parse yt-dlp metadata JSON: {e}")))?;
    Ok(VideoMetadata {
        title: json.get("title").and_then(|v| v.as_str()).map(String::from),
        uploader: json
            .get("uploader")
            .and_then(|v| v.as_str())
            .map(String::from),
        duration_seconds: json.get("duration").and_then(|v| v.as_f64()),
    })
}

/// Tries to fetch an already-existing transcript for `url`: creator
/// captions first (most accurate), then YouTube's auto-generated captions,
/// returning `Ok(None)` — not an error — if neither exists, so the caller
/// can fall back to local Whisper transcription (or report "no transcript
/// available yet" if that fallback isn't compiled into this build).
///
/// `lang` is a BCP-47-ish language code (e.g. `"en"`) to request; if that
/// exact language isn't available yt-dlp simply won't produce a file and
/// this returns `Ok(None)` rather than guessing at a different language.
pub fn fetch_captions(
    url: &str,
    workdir: &Path,
    lang: &str,
) -> Result<Option<(Transcript, TranscriptSource)>> {
    fetch_captions_with_progress(url, workdir, lang, &mut |_| {})
}

/// Same as [`fetch_captions`], but reports each step through `on_progress`
/// (e.g. "Checking for creator captions...") so a caller like the Tauri
/// import command can show the user what's happening during what would
/// otherwise look like a silent multi-second pause.
pub fn fetch_captions_with_progress(
    url: &str,
    workdir: &Path,
    lang: &str,
    on_progress: &mut dyn FnMut(&str),
) -> Result<Option<(Transcript, TranscriptSource)>> {
    std::fs::create_dir_all(workdir)?;

    on_progress("Checking for creator-provided captions...");
    if let Some(transcript) =
        fetch_caption_track(url, workdir, lang, CaptionKind::CreatorWritten)?
    {
        on_progress("Found creator-provided captions.");
        return Ok(Some((transcript, TranscriptSource::CreatorCaptions)));
    }
    on_progress("No creator captions — checking for auto-generated captions...");
    if let Some(transcript) = fetch_caption_track(url, workdir, lang, CaptionKind::AutoGenerated)?
    {
        on_progress("Found auto-generated captions.");
        return Ok(Some((transcript, TranscriptSource::AutoCaptions)));
    }
    on_progress("No existing captions found.");
    Ok(None)
}

/// Which `yt-dlp` subtitle flag to use for one attempt.
#[derive(Debug, Clone, Copy)]
enum CaptionKind {
    CreatorWritten,
    AutoGenerated,
}

impl CaptionKind {
    fn yt_dlp_flag(&self) -> &'static str {
        match self {
            CaptionKind::CreatorWritten => "--write-sub",
            CaptionKind::AutoGenerated => "--write-auto-sub",
        }
    }
}

/// Runs one `yt-dlp` subtitle-only fetch (no video/audio download) and
/// parses whatever `.vtt` file comes out, if any. `yt-dlp` exits
/// successfully even when the requested caption kind doesn't exist for a
/// video (it just doesn't produce a file) — so "no file produced" is the
/// normal, expected way to learn "not available", not an error.
fn fetch_caption_track(
    url: &str,
    workdir: &Path,
    lang: &str,
    kind: CaptionKind,
) -> Result<Option<Transcript>> {
    let job_id = uuid::Uuid::new_v4();
    let output_template = workdir.join(format!("{job_id}.%(ext)s"));

    let output = Command::new("yt-dlp")
        .args([
            kind.yt_dlp_flag(),
            "--sub-lang",
            lang,
            "--sub-format",
            "vtt",
            "--skip-download",
            "--no-playlist",
            "-o",
            &output_template.to_string_lossy(),
            url,
        ])
        .stdin(Stdio::null())
        .output()
        .map_err(|e| tooling::missing_tool_error("yt-dlp", tooling::YT_DLP_INSTALL_HINT, e))?;
    if !output.status.success() {
        return Err(CoreError::Other(format!(
            "yt-dlp failed ({}): {}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }

    let prefix = format!("{job_id}.");
    let vtt_path = std::fs::read_dir(workdir)?
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .find(|p| {
            p.file_name()
                .and_then(|n| n.to_str())
                .map(|n| n.starts_with(&prefix) && n.ends_with(".vtt"))
                .unwrap_or(false)
        });

    let Some(vtt_path) = vtt_path else {
        return Ok(None);
    };
    let vtt_text = std::fs::read_to_string(&vtt_path)?;
    let _ = std::fs::remove_file(&vtt_path);
    Ok(Some(parse_vtt(&vtt_text)))
}

/// Parses a WebVTT caption file into a [`Transcript`].
///
/// YouTube's auto-generated VTT in particular is messy in ways a naive
/// parser would badly mangle: it uses "rolling" cues where each cue
/// repeats most of the previous cue's text plus a little new text (so the
/// captions appear to scroll), and it embeds inline per-word timestamp tags
/// like `<00:00:01.360><c> word</c>` for karaoke-style highlighting. This
/// strips those inline tags and skips any cue whose text is a pure prefix
/// duplicate of the text already accumulated, so the result reads as
/// continuous prose instead of repeating itself.
pub(crate) fn parse_vtt(vtt_text: &str) -> Transcript {
    let mut segments: Vec<TranscriptSegment> = Vec::new();
    let mut last_text = String::new();

    let mut lines = vtt_text.lines().peekable();
    while let Some(line) = lines.next() {
        let Some((start_ms, end_ms)) = parse_vtt_timing_line(line) else {
            continue;
        };

        // Cue text is every following non-blank line up to the next blank
        // line or timing line.
        let mut cue_text_lines = Vec::new();
        while let Some(next) = lines.peek() {
            if next.trim().is_empty() || parse_vtt_timing_line(next).is_some() {
                break;
            }
            cue_text_lines.push(lines.next().unwrap());
        }

        let cue_text = cue_text_lines
            .last()
            .map(|line| strip_vtt_inline_tags(line))
            .unwrap_or_default();
        let cue_text = cue_text.trim();
        if cue_text.is_empty() {
            continue;
        }

        // Rolling captions: each new cue usually starts with (most of) the
        // previous cue's text. Keep only the genuinely new suffix.
        let new_text = if let Some(stripped) = cue_text.strip_prefix(last_text.as_str()) {
            stripped.trim()
        } else {
            cue_text
        };
        if new_text.is_empty() {
            continue;
        }

        segments.push(TranscriptSegment {
            start_ms,
            end_ms,
            text: new_text.to_string(),
        });
        last_text = cue_text.to_string();
    }

    Transcript::from_segments(segments)
}

/// Parses a WebVTT cue timing line (`00:00:01.360 --> 00:00:04.200 ...`)
/// into millisecond offsets, or `None` if `line` isn't a timing line.
fn parse_vtt_timing_line(line: &str) -> Option<(i64, i64)> {
    let (start, rest) = line.split_once("-->")?;
    // Positioning cue settings (e.g. "align:start position:0%") can follow
    // the end timestamp separated by whitespace; only the first token matters.
    let end = rest.split_whitespace().next()?;
    Some((parse_vtt_timestamp(start.trim())?, parse_vtt_timestamp(end)?))
}

/// Parses a single WebVTT timestamp (`HH:MM:SS.mmm` or `MM:SS.mmm`) into
/// milliseconds.
fn parse_vtt_timestamp(ts: &str) -> Option<i64> {
    let (whole, millis) = ts.split_once('.')?;
    let millis: i64 = millis.get(0..3).unwrap_or(millis).parse().ok()?;
    let parts: Vec<&str> = whole.split(':').collect();
    let (h, m, s) = match parts.as_slice() {
        [h, m, s] => (h.parse::<i64>().ok()?, m.parse::<i64>().ok()?, s.parse::<i64>().ok()?),
        [m, s] => (0, m.parse::<i64>().ok()?, s.parse::<i64>().ok()?),
        _ => return None,
    };
    Some(((h * 3600 + m * 60 + s) * 1000) + millis)
}

/// Strips WebVTT inline markup: per-word timestamp tags
/// (`<00:00:01.360>`) and styling tags (`<c>`, `</c>`, `<b>`, ...), leaving
/// plain text.
fn strip_vtt_inline_tags(text: &str) -> String {
    let mut result = String::with_capacity(text.len());
    let mut in_tag = false;
    for ch in text.chars() {
        match ch {
            '<' => in_tag = true,
            '>' => in_tag = false,
            _ if !in_tag => result.push(ch),
            _ => {}
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_vtt_timestamp_handles_both_formats() {
        assert_eq!(parse_vtt_timestamp("00:00:01.360"), Some(1360));
        assert_eq!(parse_vtt_timestamp("01:02:03.000"), Some(3_723_000));
        assert_eq!(parse_vtt_timestamp("02:03.500"), Some(123_500));
        assert_eq!(parse_vtt_timestamp("not a timestamp"), None);
    }

    #[test]
    fn strip_vtt_inline_tags_removes_word_timing_and_style_tags() {
        assert_eq!(
            strip_vtt_inline_tags("<00:00:01.360><c> Hello</c> <00:00:01.900><c> world</c>"),
            " Hello  world"
        );
        assert_eq!(strip_vtt_inline_tags("plain text"), "plain text");
    }

    #[test]
    fn parse_vtt_extracts_simple_non_rolling_cues() {
        let vtt = "WEBVTT\n\n\
            00:00:00.000 --> 00:00:02.000\n\
            Hello there.\n\n\
            00:00:02.000 --> 00:00:04.000\n\
            How are you?\n";
        let transcript = parse_vtt(vtt);
        assert_eq!(transcript.segments.len(), 2);
        assert_eq!(transcript.segments[0].text, "Hello there.");
        assert_eq!(transcript.segments[0].start_ms, 0);
        assert_eq!(transcript.segments[0].end_ms, 2000);
        assert_eq!(transcript.segments[1].text, "How are you?");
        assert_eq!(transcript.full_text, "Hello there. How are you?");
    }

    #[test]
    fn parse_vtt_deduplicates_rolling_youtube_auto_captions() {
        // Real YouTube auto-caption VTT repeats the previous cue's text
        // plus new words, with per-word timing tags mixed in.
        let vtt = "WEBVTT\n\n\
            00:00:00.000 --> 00:00:02.000 align:start position:0%\n\
            <00:00:00.160><c> Hello</c><00:00:00.320><c> there</c>\n\
            Hello there\n\n\
            00:00:02.000 --> 00:00:04.000 align:start position:0%\n\
            Hello there\n\
            Hello there<00:00:02.400><c> how</c><00:00:02.720><c> are</c>\n\n\
            00:00:04.000 --> 00:00:06.000 align:start position:0%\n\
            Hello there how are\n\
            Hello there how are you\n";
        let transcript = parse_vtt(vtt);
        assert_eq!(transcript.full_text, "Hello there how are you");
    }

    #[test]
    fn parse_vtt_ignores_header_and_blank_lines() {
        let transcript = parse_vtt("WEBVTT\nKind: captions\nLanguage: en\n\n");
        assert!(transcript.segments.is_empty());
        assert_eq!(transcript.full_text, "");
    }
}
